#!/bin/bash

echo "📱 Xcode Navigation Guide"
echo ""
echo "After Xcode opens, look for:"
echo ""
echo "LEFT SIDEBAR:"
echo "  └─ Runner (blue icon) ← PROJECT"
echo "      └─ TARGETS"
echo "          └─ Runner ← CLICK THIS!"
echo ""
echo "MAIN AREA (after clicking Runner target):"
echo "  Tabs at top:"
echo "  [General] [Signing & Capabilities] [Build Settings] ..."
echo ""
echo "  Click: Signing & Capabilities"
echo ""
echo "In that tab, you'll see:"
echo "  ☑ Automatically manage signing"
echo "  Team: [Select Team ▼]"
echo ""
echo "📸 Take a screenshot (⌘+Shift+4) and share what you see!"
echo ""
